name: Build Packages
on: [push, pull_request, workflow_dispatch]
jobs:
  Build-Windows-32bit-VS2019:
    name: 32-bit Windows On VS2019
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '[16.0, 17.0)'
      - run: msbuild -m "engine/compilers/VisualStudio 2019/Torque 2D.sln" /p:Configuration=Debug /p:Platform=win32
      - run: msbuild -m "engine/compilers/VisualStudio 2019/Torque 2D.sln" /p:Configuration=Release /p:Platform=win32
      - uses: actions/upload-artifact@v2
        with:
          name: Torque2D_Windows_x86_32bit_VS2019
          path: |
            .
            ! .git/
            ! engine/
  Build-Windows-64bit-VS2019:
    name: 64-bit Windows On VS2019
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '[16.0, 17.0)'
          msbuild-architecture: x64
      - run: msbuild -m "engine/compilers/VisualStudio 2019/Torque 2D.sln" /p:Configuration=Debug /p:Platform=x64
      - run: msbuild -m "engine/compilers/VisualStudio 2019/Torque 2D.sln" /p:Configuration=Release /p:Platform=x64
      - uses: actions/upload-artifact@v2
        with:
          name: Torque2D_Windows_x86_64bit_VS2019
          path: |
            .
            ! .git/
            ! engine/
  Build-Windows-32bit-VS2022:
    name: 32-bit Windows On VS2022
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '[17.0, 18.0)'
      - run: msbuild -m "engine/compilers/VisualStudio 2022/Torque 2D.sln" /p:Configuration=Debug /p:Platform=win32
      - run: msbuild -m "engine/compilers/VisualStudio 2022/Torque 2D.sln" /p:Configuration=Release /p:Platform=win32
      - uses: actions/upload-artifact@v2
        with:
          name: Torque2D_Windows_x86_32bit_VS2022
          path: |
            .
            ! .git/
            ! engine/
  Build-Windows-64bit-VS2022:
    name: 64-bit Windows On VS2022
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '[17.0, 18.0)'
          msbuild-architecture: x64
      - run: msbuild -m "engine/compilers/VisualStudio 2022/Torque 2D.sln" /p:Configuration=Debug /p:Platform=x64
      - run: msbuild -m "engine/compilers/VisualStudio 2022/Torque 2D.sln" /p:Configuration=Release /p:Platform=x64
      - uses: actions/upload-artifact@v2
        with:
          name: Torque2D_Windows_x86_64bit_VS2022
          path: |
            .
            ! .git/
            ! engine/
  Build-Linux-32Bit:
    name: Build package for 32-bit x86 Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd engine/compilers/Make-32bit/ && make
      - uses: actions/upload-artifact@v2
        with:
          name: Torque2D_Linux_x86_32bit
          path: |
            .
            ! .git/
            ! engine/
  Build-Linux-64bit:
    name: Build package for 64-bit x86 Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd engine/compilers/Make-64bit/ && make
      - uses: actions/upload-artifact@v2
        with:
          name: Torque2D_Linux_x86_64bit
          path: |
            .
            ! .git/
            ! engine/
  Build-MacOS:
    name: Build package for MacOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd engine/compilers/Xcode && xcodebuild -project Torque2D.xcodeproj
      - uses: actions/upload-artifact@v2
        with:
          name: Torque2D_MacOS
          path: |
            .
            ! .git/
            ! engine/
  Build-iOS:
    name: Build package for iOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd engine/compilers/Xcode_iOS && xcodebuild CODE_SIGNING_ALLOWED=no -project Torque2D.xcodeproj
      - uses: actions/upload-artifact@v2
        with:
          name: Torque2D_iOS
          path: |
            .
            ! .git/
            ! engine/
